<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'BaseController' => $baseDir . '/app/controllers/BaseController.php',
    'Business\\busOrderds' => $baseDir . '/app/business/busOrderds.php',
    'Business\\busPinyin' => $baseDir . '/app/business/busPinyin.php',
    'Business\\busSms' => $baseDir . '/app/business/busSms.php',
    'Business\\busUlitity' => $baseDir . '/app/business/busUlitity.php',
    'Contact' => $baseDir . '/app/models/Contact.php',
    'Coupon' => $baseDir . '/app/models/Coupon.php',
    'Customer' => $baseDir . '/app/models/Customer.php',
    'DatabaseSeeder' => $baseDir . '/app/database/seeds/DatabaseSeeder.php',
    'Dealer' => $baseDir . '/app/models/Dealer.php',
    'HomeController' => $baseDir . '/app/controllers/HomeController.php',
    'IlluminateQueueClosure' => $vendorDir . '/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php',
    'Login' => $baseDir . '/app/models/Login.php',
    'Order' => $baseDir . '/app/models/Order.php',
    'OrderController' => $baseDir . '/app/controllers/OrderController.php',
    'OrderDiscount' => $baseDir . '/app/models/OrderDiscount.php',
    'OrderDishFlash' => $baseDir . '/app/models/OrderDishFlash.php',
    'OrderStatusMessage' => $baseDir . '/app/models/OrderStatusMessage.php',
    'Pic' => $baseDir . '/app/models/Pic.php',
    'Product' => $baseDir . '/app/models/Product.php',
    'ProductCategory' => $baseDir . '/app/models/ProductCategory.php',
    'ProductCategoryRelation' => $baseDir . '/app/models/ProductCategoryRelation.php',
    'ProductController' => $baseDir . '/app/controllers/ProductController.php',
    'SessionHandlerInterface' => $vendorDir . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/SessionHandlerInterface.php',
    'Symfony\\Component\\HttpFoundation\\Resources\\stubs\\FakeFile' => $vendorDir . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/FakeFile.php',
    'TestCase' => $baseDir . '/app/tests/TestCase.php',
    'UserController' => $baseDir . '/app/controllers/UserController.php',
    'Whoops\\Module' => $vendorDir . '/filp/whoops/src/deprecated/Zend/Module.php',
    'Whoops\\Provider\\Zend\\ExceptionStrategy' => $vendorDir . '/filp/whoops/src/deprecated/Zend/ExceptionStrategy.php',
    'Whoops\\Provider\\Zend\\RouteNotFoundStrategy' => $vendorDir . '/filp/whoops/src/deprecated/Zend/RouteNotFoundStrategy.php',
);
